# f=open("file.txt","x")
f=open("file.txt","w")
f.write("hello world")
f.close()
f=open("file.txt","r")
# file=open("newwwfile.txt","x")
r=f.read()
file=open("newwwfile.txt","w")
print(file.write(r))
